### ISSUE TITLE
Check if the session has expired

### ISSUE THREAD

**Issue by Harmageddon** [DivineThreepwood/bcozy#16]
At the moment, the login panel shows that the user is still logged in, even if the session has expired and thus, actions have failed.

TODO: 
Show overlay to inform user about logout

**Comment by Zukye** [comment]
@pLeminoq aktuell wird der Observer nicht benachrichtigt wenn man sich ausloggt (oder ausgeloggt wird), da die Observer mit null informiert werden, aber die Observable kein null weiterleiten. (soweit ich das jetzt sehe) 
Bsp: SessionManager:367  ` loginObervable.notifyObservers(null);`
und:
AbstractObservable:114  ` if(observable == null) { LOGGER.debug("Skip notification because Observable is null!");
`

**Comment by pLeminoq** [comment]
That is correct. I just fixed that in the authentication project. Now even on logout the string userId@clientId is notified which is just @ in this case. So you can either check if this is the string you have been notified with or just use the isLoggedIn method of the session manager to check if its a logout.

**Comment by DivineThreepwood** [comment]
bcozy development has been freezed.
