### ISSUE TITLE
Consumption for rooms is 0

### ISSUE THREAD

**Issue by rlipperts** [DivineThreepwood/bcozy#95]
Calling the database with the location ID of a room does not yield the summed up power consumption, so all consumers in that room need to be called and added up

**Comment by DivineThreepwood** [comment]
Since there is no representation of "rooms" in bco, please define in more detail what you are referring to. Furthermore, please define what kind of databases you are referring to?
* Influx db 
  * can you confirm, that the db contains location consumption entries within the queried time window? 
* Registry db?
   * The registry only includes unit configs and no service states at all

**Comment by rlipperts** [comment]
The two bugs I posted are directly concerning the commits I pushed to the feature-power-terminal-sidebar branch

**Comment by rlipperts** [comment]
And they are just a simple reminder which aspects I still need to fix, but sadly I cannot refer branches in issues in wonderful ZenHub
